-- 045_fiscal_review_system.sql
-- Interactive fiscal review system: structured alerts from Sonnet escalation.
-- invoice_notes stores FiscalAlert[] JSON on invoice_classifications.
-- has_fiscal_alerts on invoices enables list filtering and badges.

-- Structured fiscal alerts generated by Sonnet escalation
ALTER TABLE public.invoice_classifications
  ADD COLUMN IF NOT EXISTS invoice_notes jsonb;

-- Quick flag for invoice list filtering/badges
ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS has_fiscal_alerts boolean DEFAULT false;

-- Index for filtering invoices with fiscal alerts
CREATE INDEX IF NOT EXISTS idx_invoices_fiscal_alerts
  ON public.invoices (has_fiscal_alerts)
  WHERE has_fiscal_alerts = true;
